# Generated by Django 5.2.17 on 2026-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=32)),
                ('model_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('endpoint_kind', models.CharField(choices=[('chat_completions', 'Chat completions'), ('responses', 'Responses')], max_length=32)),
                ('input_cost_per_1m', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('output_cost_per_1m', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('max_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('max_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('default_temperature', models.FloatField(blank=True, null=True)),
                ('supports_json_mode', models.BooleanField(default=False)),
                ('is_agent_capable', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('api_seen_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_notes', models.TextField(blank=True, default='')),
                ('extra_params', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['provider', 'model_id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_id'), name='uniq_provider_model_id')],
            },
        ),
    ]
